// Generated by CodiumAI

import { describe, expect, it } from 'vitest';
import { renderWithProviders } from '../../test/test-utils';
import MainPage from '../pages';
import { screen } from '@testing-library/dom';

describe('MainPage', () => {
	renderWithProviders(<MainPage />);

	it('render banner with AmensGood', async () => {
		expect(
			screen.getByRole('banner', { name: /AmensGood/i })
		).toBeInTheDocument();
	});

	expect(
		screen.getByText(
			'Week 3 - React. Task #3 Redux. Redux Toolkit, RTK Query. Context api'
		)
	).toBeInTheDocument();
	expect(
		screen.getByText('To start your expedition please choose category below')
	).toBeInTheDocument();

	expect(screen.getByRole('contentinfo')).toBeInTheDocument();
	expect(screen.getByText(/tabs Loading/i)).toBeInTheDocument();
});
