// Generated by CodiumAI

import { renderHook } from '@testing-library/react';
import { act, useState } from 'react';
import { describe, expect, it } from 'vitest';
import { ThemeType } from './App';

describe('App', () => {
	// Theme changes from Dark to Light and vice versa when handleChangeTheme is called
	it('should toggle theme from Dark to Light and vice versa when handleChangeTheme is called', () => {
		const { result } = renderHook(() => useState<ThemeType>('Dark'));
		const [, setTheme] = result.current;

		act(() => {
			setTheme((prevTheme) => (prevTheme === 'Dark' ? 'Light' : 'Dark'));
		});

		expect(result.current[0]).toBe('Light');

		act(() => {
			setTheme((prevTheme) => (prevTheme === 'Dark' ? 'Light' : 'Dark'));
		});

		expect(result.current[0]).toBe('Dark');
	});

	// handleChangeTheme is called multiple times in quick succession
	it('should handle multiple quick calls to handleChangeTheme correctly', () => {
		const { result } = renderHook(() => useState<ThemeType>('Dark'));
		const [, setTheme] = result.current;

		act(() => {
			setTheme((prevTheme) => (prevTheme === 'Dark' ? 'Light' : 'Dark'));
			setTheme((prevTheme) => (prevTheme === 'Dark' ? 'Light' : 'Dark'));
			setTheme((prevTheme) => (prevTheme === 'Dark' ? 'Light' : 'Dark'));
		});

		expect(result.current[0]).toBe('Light');
	});
});
