// Generated by CodiumAI

import { describe, expect, it, vi } from 'vitest';
import MainPage from '.';
import { screen } from '@testing-library/dom';
import { renderWithProviders } from '../test/test-utils';
import { AppRouterContextProviderMock } from '../test/AppRouterContextProviderMock';

describe('MainPage', () => {
	vi.mock('next/router', () => ({
		useRouter: () => ({
			push: vi.fn(),
			query: {},
		}),
	}));

	it('heading with week data', () => {
		renderWithProviders(
			<AppRouterContextProviderMock router={{}}>
				<MainPage />
			</AppRouterContextProviderMock>,
		);
		expect(
			screen.getByText(
				'Week 3 - React. Task #3 Redux. Redux Toolkit, RTK Query. Context api',
			),
		).toBeInTheDocument();
	});
	it('render tips', () => {
		renderWithProviders(
			<AppRouterContextProviderMock router={{}}>
				<MainPage />
			</AppRouterContextProviderMock>,
		);
		expect(
			screen.getByText('To start your expedition please choose category below'),
		).toBeInTheDocument();
	});
	it('render loading placeholder', () => {
		renderWithProviders(
			<AppRouterContextProviderMock router={{}}>
				<MainPage />
			</AppRouterContextProviderMock>,
		);
		expect(screen.getByText(/tabs Loading/i)).toBeInTheDocument();
	});
});
